### ISSUE TITLE
Branch Merge Discussion

### ISSUE THREAD

**Issue by kevdagoat** [kevdagoat/hack-technicolor#25]
@LuKePicci @flywire Safe to merge lastest to stable?

**Comment by flywire** [comment]
Maybe resolve https://hack-technicolor.readthedocs.io/en/latest/Resources/#examples Decrypting Firmware osck source

**Comment by flywire** [comment]
Missing https://hack-technicolor.readthedocs.io/en/latest/Resources/ Table of contents items

**Comment by LuKePicci** [comment]
So, can I go ahead uploading keys?

**Comment by kevdagoat** [comment]
@LuKePicci think so

**Comment by nutterthanos** [comment]
The keys are uploaded.

**Comment by kevdagoat** [comment]
Ok @flywire @LuKePicci will sync tonight

**Comment by flywire** [comment]
I'll send a few comments beforehand.

**Comment by kevdagoat** [comment]
Ok conmmits??

**Comment by flywire** [comment]
Comments in attached documents. One cleaned image.

Sorry, off to bed.

BTW
Have a quick look at
https://hack-technicolor.readthedocs.io/en/latest/Hack%20Type%201&2/#type-1-flash-of-type-2-then-root
(which
should be published today).

Response

Thanks. However, the information in your link seems not clear to me but the
information in the following link seems acceptable for me.

/wiki/hack_technicolor#hw_model_1622
<https://whirlpool.net.au/wiki/hack_technicolor#hw_model_1622>

**Comment by flywire** [comment]
I meant to add there might be a problem that the root Type 1/2 is not easy
enough for noobs and we might be too familiar with it to pick that up.

Guide and WP wiki really needs testing with forum members. Need to post
links to both and ask to compare and comment.

**Comment by flywire** [comment]
Uploaded documents lost by github.

**Comment by LuKePicci** [comment]
Almost all is fine for me, apply all patches you suggested in comments. Only some notes:
- Type 2 RBI is needed for recovery purposes, it's mentioned in requirements because whatever Type of firmware users have at that moment we told them to go offline.
- All MST firmwares are no-brand firmwares, mst is the third party remote management platform for unbranded devices
- Do not move those two sections infobox about permanent ssh access, I put there because people may be tempted to stop as soon as they get a root shell
- Standard RTFD behaviour does not break if you follow the guide on the wiki. It breaks only if you install some heavy mod like the custom tch-nginx-gui where the RTFD scripts are modded as well. We could say "ask your modder if RTFD still works in your situation"

**Comment by flywire** [comment]
@kevdagoat needs final sweep, especially links

**Comment by kevdagoat** [comment]
Ok will get it done this week

**Comment by kevdagoat** [comment]
I am going to close for now
