### ISSUE TITLE
Add Arcadyan LH1000 exploits?

### ISSUE THREAD

**Issue by damolp** [kevdagoat/hack-technicolor#83]
**Describe Feature Request**
I've got a bunch of exploits (read: 0-Days) for the Arcadyan version of the Telstra Smart Modem Gen 2 (LH1000 model). Would it make sense to add them here? (even though they are from a different manufacturer)

**Comment by kevdagoat** [comment]
Hi @damolp 

I think this wouldn't be the right place for such instructions, as it is mainly a Technicolor focused wiki 😅 
I would suggest that you create a community thread on [Whirlpool Forums](https://forums.whirlpool.net.au/forum/82) and post your findings there, so they can be tested and a group of willing hackers assembled. Once this community is capable of developing software for the device, i would then recommend setting up a guide like this (feel free to fork and entirely change the content!) to allow novices to unlock these devices. I would be keen to see how these exploits progress!

I sadly don't have an Arcadyan modem, nor any of the core community members, otherwise i would happily pitch in. Feel free to PM me if you want any help: https://forums.whirlpool.net.au/user/812876

**Comment by flywire** [comment]
@damolp - flick [flywire](https://forums.whirlpool.net.au/user/467089) a copy of the exploits too.

**Comment by shaananc** [comment]
Hi @damolp -- did you end up posting these anywhere?

**Comment by byteman-solutions** [comment]
> Hi @damolp -- did you end up posting these anywhere?

Hey @damolp , I'm very interested too! I have a substantial amount of these modems laying around so would love to spend some time fiddling with these (along with the DJA0231s I have too!)

**Comment by damolp** [comment]
> > Hi @damolp -- did you end up posting these anywhere?
> 
> Hey @damolp , I'm very interested too! I have a substantial amount of these modems laying around so would love to spend some time fiddling with these (along with the DJA0231s I have too!)

I've given mine to my mate so I no longer have one to experiment with atm (he didn't have internet at his new place and the 4G was still working lol, turn off all the phone home stuff and you get free 25/2 internet ;) ).

I'll grab it off him and see if I can get the firmware version and pull out the exploits from the httpd binary again. IIRC it was on the ping/traceroute page as the webserver runs as root and it does a bunch of `execve` stuff straight out to the binaries in `sbin`.

If there's enough interest we should start a community or slack/discord/github project/whatnot.

**Comment by shaananc** [comment]
I found an exploit. Lets set up something to make it workable, before posting it, so that people can flash their routers before there is a fix. @flywire @damolp @byteman-solutions -- Slack https://join.slack.com/t/telstrce/shared_invite/zt-g2ma5hza-g3dcDmY0tMNJYYrOn2PRSA

and hack-technicolor we'll get out of your hair.

**Comment by gtrboy** [comment]
> **Describe Feature Request**
> I've got a bunch of exploits (read: 0-Days) for the Arcadyan version of the Telstra Smart Modem Gen 2 (LH1000 model). Would it make sense to add them here? (even though they are from a different manufacturer)

Hi @damolp , I noticed that the firmware image of LH1000 modem is encrypted, so could you tell me how to get the files in the image? or you extract them from UART? Thank you
